export const SET_USER = "SET_USER"
export const CHOOSE_STORE = "CHOOSE_STORE"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADJUST_QTY = "ADJUST_QTY"
export const UPDATE_TO_CART = "UPDATE_TO_CART"